/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gymadminnh.ui;

import gymadminnh.data.Cliente;
import gymadminnh.data.DataUtils;
import gymadminnh.data.MedidasCliente;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author joel
 */
public class JFrameMedidas extends javax.swing.JFrame {
    
    /**
     *  ACCIONES
     *  FALSE - MODIFICAR MEDIDAS
     *  TRUE - AGREGAR MEDIDAS
     */
    
    private static Cliente cliente;
    private static boolean esNuevo;
    private static MedidasCliente medida = null;

    /**
     * Creates new form JFrameMedidas
     */
    public JFrameMedidas(boolean b, Cliente c) {
        cliente = c;
        initComponents();
        esNuevo = b;
        if ( esNuevo ){
            medida = new MedidasCliente();
        } else {
            int tamanoLista = cliente.getListaMedidas().size();
            medida = cliente.getListaMedidas().get(tamanoLista-1);
            cargarUltimaMedida();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jtfBicepDerecho = new javax.swing.JTextField();
        jtfBicepIzqierdo = new javax.swing.JTextField();
        jtfPectoral = new javax.swing.JTextField();
        jtfAbdomen = new javax.swing.JTextField();
        jtfCintura = new javax.swing.JTextField();
        jtfPeso = new javax.swing.JTextField();
        jtfGluteos = new javax.swing.JTextField();
        jtfCadera = new javax.swing.JTextField();
        jtfPiernaDerecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfPiernaIzq = new javax.swing.JTextField();
        jbuttonCancelar = new javax.swing.JButton();
        jbuttonGuardarMedidas = new javax.swing.JButton();
        jxdatepickerFecha = new org.jdesktop.swingx.JXDatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medidas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Editar Medidas"));

        jLabel21.setText("Fecha");

        jLabel20.setText("Bicep Derecho");

        jLabel22.setText("Pectoral");

        jLabel23.setText("Abdomen");

        jLabel24.setText("Cintura");

        jLabel27.setText("Pierna Derecha");

        jLabel26.setText("Cadera");

        jLabel25.setText("Gluteos");

        jLabel28.setText("Peso");

        jLabel1.setText("Bicep Izquierdo");

        jLabel2.setText("Pierna Izquierda");

        jbuttonCancelar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonCancelar.setText("Cancelar");
        jbuttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCancelarActionPerformed(evt);
            }
        });

        jbuttonGuardarMedidas.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonGuardarMedidas.setText("Guardar");
        jbuttonGuardarMedidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonGuardarMedidasActionPerformed(evt);
            }
        });

        jxdatepickerFecha.setDate(new Date());
        this.jxdatepickerFecha.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonCancelar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel1)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfBicepDerecho, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jtfBicepIzqierdo)
                                    .addComponent(jtfPectoral)
                                    .addComponent(jtfAbdomen)
                                    .addComponent(jtfCintura))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel2)
                                    .addComponent(jbuttonGuardarMedidas))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jtfGluteos)
                                    .addComponent(jtfCadera)
                                    .addComponent(jtfPiernaDerecha)
                                    .addComponent(jtfPiernaIzq)))
                            .addComponent(jxdatepickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jxdatepickerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBicepDerecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jtfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBicepIzqierdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGluteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPectoral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel26)
                    .addComponent(jtfCadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jtfPiernaDerecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPiernaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbuttonCancelar)
                    .addComponent(jbuttonGuardarMedidas))
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbuttonCancelarActionPerformed

    private void jbuttonGuardarMedidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonGuardarMedidasActionPerformed
        if ( datosValidados()) {
            int resultado = 0;
            if (!esNuevo) {
                resultado = new DataUtils().modificarMedidasDB(medida);
            } else {
                resultado = new DataUtils().agregarMedidasDB(medida, cliente.getIdCliente());
            }
            System.out.println("result: " + resultado);
            if (resultado == 1) {
                JOptionPane.showMessageDialog(this, "Datos guardados.");
                ArrayList<MedidasCliente> almc = new DataUtils().getMedidasCliente(cliente.getIdCliente());
                cliente.setListaMedidas(almc);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al guardar los datos. Los datos no han sido guardados.");
                this.dispose();
            }
        }
    }//GEN-LAST:event_jbuttonGuardarMedidasActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMedidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrameMedidas(esNuevo, cliente).setVisible(true);
            }
        });
    }
    
    private boolean esNumero(String text) {
        try {
            double d = Double.parseDouble(text);
        } catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
    
    private boolean sonNumero(String [] strs) {
        for (String text : strs) {
            try {
                double d = Double.parseDouble(text);
            } catch (NumberFormatException nfe) {
                return false;
            }
        }
        return true;
    }

    private boolean tienenInfo(String [] strs) {
        for (String str : strs ){
            if ( str.isEmpty() )
                return false;
            if ( str.split(" ").length < 1 )
                return false;
        }
        return true;
    }

    private boolean datosValidados() {
        String strBicepDer = this.jtfBicepDerecho.getText();
        String strBicepIzq = this.jtfBicepIzqierdo.getText();
        String strPectoral = this.jtfPectoral.getText();
        String strAbdomen = this.jtfAbdomen.getText();
        String strCintura = this.jtfCintura.getText();
        String [] strs = {strBicepDer, strBicepIzq, strPectoral, strAbdomen, strCintura};
        
        if ( !tienenInfo(strs) ){
            JOptionPane.showMessageDialog(this, "Biceps, Pectoral, Abdomen y Cintura son datos obligatorios.");
            return false;
        } else if ( !sonNumero(strs) ) {
            JOptionPane.showMessageDialog(this, "Error en el formato de campos obligatorios.");
            return false;
        } else {
            String strPeso = this.jtfPeso.getText();
            String strGluteos = this.jtfGluteos.getText();
            String strCadera = this.jtfCadera.getText();
            String strPiernaDer = this.jtfPiernaDerecha.getText();
            String strPiernaIzq = this.jtfPiernaIzq.getText();

            if (!strPeso.isEmpty()) {
                if (esNumero(strPeso)) {
                    medida.setPeso(Double.parseDouble(strPeso));
                } else {
                    JOptionPane.showMessageDialog(this, "Solo valores numericos.");
                    return false;
                }
            }
            if (!strGluteos.isEmpty()) {
                if (esNumero(strGluteos)) {
                    medida.setGluteos(Double.parseDouble(strGluteos));
                } else {
                    JOptionPane.showMessageDialog(this, "Solo valores numericos.");
                    return false;
                }
            }
            if (!strCadera.isEmpty()) {
                if (esNumero(strCadera)) {
                    medida.setCadera(Double.parseDouble(strCadera));
                } else {
                    JOptionPane.showMessageDialog(this, "Solo valores numericos.");
                    return false;
                }
            }
            if (!strPiernaDer.isEmpty()) {
                if (esNumero(strPiernaDer)) {
                    medida.setPiernaDer(Double.parseDouble(strPiernaDer));
                } else {
                    JOptionPane.showMessageDialog(this, "Solo valores numericos.");
                    return false;
                }
            }
            if (!strPiernaIzq.isEmpty()) {
                if (esNumero(strPiernaIzq)) {
                    medida.setPiernaIzq(Double.parseDouble(strPiernaIzq));
                } else {
                    JOptionPane.showMessageDialog(this, "Solo valores numericos.");
                    return false;
                }
            }
            
            medida.setBicepDer(Double.parseDouble(strBicepDer));
            medida.setBicepIzq(Double.parseDouble(strBicepIzq));
            medida.setPectoral(Double.parseDouble(strPectoral));
            medida.setAbdomen(Double.parseDouble(strAbdomen));
            medida.setCintura(Double.parseDouble(strCintura));
            
            Date fecha = this.jxdatepickerFecha.getDate();
            medida.setFecha(fecha);
            return true;

        }
    }
    
    private void cargarUltimaMedida() {
        this.jxdatepickerFecha.setDate(medida.getFecha());
        this.jtfBicepDerecho.setText(String.valueOf(medida.getBicepDer()));
        this.jtfBicepIzqierdo.setText(String.valueOf(medida.getBicepIzq()));
        this.jtfPectoral.setText(String.valueOf(medida.getPectoral()));
        this.jtfAbdomen.setText(String.valueOf(medida.getAbdomen()));
        this.jtfCintura.setText(String.valueOf(medida.getCintura()));
        this.jtfPeso.setText(String.valueOf(medida.getPeso()));
        this.jtfGluteos.setText(String.valueOf(medida.getGluteos()));
        this.jtfCadera.setText(String.valueOf(medida.getCadera()));
        this.jtfPiernaDerecha.setText(String.valueOf(medida.getPiernaDer()));
        this.jtfPiernaIzq.setText(String.valueOf(medida.getPiernaIzq()));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbuttonCancelar;
    private javax.swing.JButton jbuttonGuardarMedidas;
    private javax.swing.JTextField jtfAbdomen;
    private javax.swing.JTextField jtfBicepDerecho;
    private javax.swing.JTextField jtfBicepIzqierdo;
    private javax.swing.JTextField jtfCadera;
    private javax.swing.JTextField jtfCintura;
    private javax.swing.JTextField jtfGluteos;
    private javax.swing.JTextField jtfPectoral;
    private javax.swing.JTextField jtfPeso;
    private javax.swing.JTextField jtfPiernaDerecha;
    private javax.swing.JTextField jtfPiernaIzq;
    private org.jdesktop.swingx.JXDatePicker jxdatepickerFecha;
    // End of variables declaration//GEN-END:variables
}
