/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gymadminnh.main;

import com.jidesoft.swing.AutoCompletionComboBox;
import gymadminnh.data.*;
import gymadminnh.ui.JFrameCliente;
import gymadminnh.ui.JFrameMedidas;
import gymadminnh.ui.JFrameMembresia;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author joel
 */
public class Inicio extends javax.swing.JFrame {

    private String[] nombres;
    private Cliente clienteActual = new Cliente();
    private Cliente asistenteActual = new Cliente();
    private ArrayList<Cliente> listaClientes = new ArrayList<Cliente>();
    
    /**
     * Creates new form Inicio
     */
    public Inicio() {
        nombres = new DataUtils().getListaNombres();
        initComponents();
        limpiarClientesLabels();
    }
    
    public void actualizarClienteActual(){
        limpiarClientesLabels();
        cargarDatosGenerales();
        cargarMedidas();
        cargarMembresias();
    }
    
    public void actualizarAsistenteActual(){
        limpiaAsistenciaNueva();
        this.jlabelAsistenciasNombre.setText(asistenteActual.getNombre());
        if (asistenteActual.getListaAsistencias().size() > 0) {
            int li = asistenteActual.getListaAsistencias().size() - 1;
            Asistencia ultimaAsistencia = asistenteActual.getListaAsistencias().get(li);
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            this.jlabelAsistenciaUltimaFecha.setText(sdf.format(ultimaAsistencia.getFechaAsistencia()));
        } else {
            JOptionPane.showMessageDialog(this, "El cliente no tiene asistencias pasadas.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelClienteDatos2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jbuttonMostrarCliente = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlabelNombre = new javax.swing.JLabel();
        jbuttonEditarCliente = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jlabelTelefono = new javax.swing.JLabel();
        jlabelEdad = new javax.swing.JLabel();
        jlabelDireccion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabelEmail = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jbuttonMedidasAgregar = new javax.swing.JButton();
        jlabelMedidaFecha = new javax.swing.JLabel();
        jlabelMedidaBiceps = new javax.swing.JLabel();
        jlabelMedidaPectoral = new javax.swing.JLabel();
        jlabelMedidaAbdomen = new javax.swing.JLabel();
        jlabelMedidaCintura = new javax.swing.JLabel();
        jlabelMedidaPeso = new javax.swing.JLabel();
        jlabelMedidaGluteos = new javax.swing.JLabel();
        jlabelMedidaCadera = new javax.swing.JLabel();
        jlabelMedidaPiernas = new javax.swing.JLabel();
        jbuttonMedidasEditar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jbuttonMembresiaAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jlabelMembresiaVence = new javax.swing.JLabel();
        jlabelMembresiaPrecio = new javax.swing.JLabel();
        jxlabelMembresiaDescripcion = new org.jdesktop.swingx.JXLabel();
        jbuttonMembresiaEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbuttonNuevoCliente = new javax.swing.JButton();
        autoComboBoxClientes = new com.jidesoft.swing.AutoCompletionComboBox();
        autoComboBoxClientes.setStrict(false);
        actualizarListaNombres(autoComboBoxClientes);
        jbuttonActualizarListaNombresClientes = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jxdatepickerAsistenciasNuevaFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel37 = new javax.swing.JLabel();
        jbuttonGuardarAsistencia = new javax.swing.JButton();
        autocomboboxAsistencias = new com.jidesoft.swing.AutoCompletionComboBox();
        autocomboboxAsistencias.setStrict(false);
        actualizarListaNombres(autocomboboxAsistencias);
        jbuttonActualizarListaNombresAsistencias = new javax.swing.JButton();
        jcbHoras = new javax.swing.JComboBox();
        jcbMins = new javax.swing.JComboBox();
        jbuttonMostrarAsistencia = new javax.swing.JButton();
        jlabelAsistenciaUltimaFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabelAsistenciasNombre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jxdatepickerAsistenciasDelDia = new org.jdesktop.swingx.JXDatePicker();
        jLabel38 = new javax.swing.JLabel();
        jbuttonActualizarTablaAsistencias = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jxdatepickerFinanzasNuevo = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        jtfFinanzasCosto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfFinanzasDescr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jbuttonFinanzasGuardar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jcbFinanzasTipo = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jcbFinanzasMes = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jtfFinanzasResumenAno = new javax.swing.JTextField();
        jbuttonFinanzasMostrarResumen = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jcbResumenMembsMes = new javax.swing.JComboBox();
        jtfResumenMembsAno = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtableResumenMembresias = new javax.swing.JTable();
        jbuttonResumenMembresiasMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelPrincipal.setPreferredSize(new java.awt.Dimension(766, 643));

        panelClienteDatos2.setMaximumSize(new java.awt.Dimension(750, 550));
        panelClienteDatos2.setPreferredSize(new java.awt.Dimension(650, 520));

        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel11.setText("Datos de Cliente");

        jbuttonMostrarCliente.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jbuttonMostrarCliente.setText("Mostrar");
        jbuttonMostrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMostrarClienteActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));

        jLabel19.setText("Nombre:");

        jLabel12.setText("Telefono:");

        jLabel13.setText("Direccion:");

        jlabelNombre.setText("{nombre}");

        jbuttonEditarCliente.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonEditarCliente.setText("Editar");
        jbuttonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonModificarClienteActionPerformed(evt);
            }
        });

        jLabel41.setText("Edad");

        jlabelTelefono.setText("{telefono}");

        jlabelEdad.setText("{edad}");

        jlabelDireccion.setText("{direccion}");

        jLabel2.setText("E-mail");

        jlabelEmail.setText("{email}");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlabelTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                            .addComponent(jlabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41)
                            .addComponent(jLabel2))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelEmail)
                            .addComponent(jlabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonEditarCliente)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jlabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jlabelTelefono)
                            .addComponent(jLabel41)
                            .addComponent(jlabelEdad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlabelDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addComponent(jlabelEmail))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbuttonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ultimas Medidas"));

        jLabel20.setText("Biceps Der/Izq");

        jLabel21.setText("Fecha");

        jLabel22.setText("Pectoral");

        jLabel23.setText("Abdomen");

        jLabel24.setText("Cintura");

        jLabel25.setText("Gluteos");

        jLabel26.setText("Cadera");

        jLabel27.setText("Pierna Der/Izq");

        jLabel28.setText("Peso");

        jbuttonMedidasAgregar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonMedidasAgregar.setText("Agregar");
        jbuttonMedidasAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMedidasAgregarActionPerformed(evt);
            }
        });

        jlabelMedidaFecha.setText("{}");

        jlabelMedidaBiceps.setText("0.0");

        jlabelMedidaPectoral.setText("0.0");

        jlabelMedidaAbdomen.setText("0.0");

        jlabelMedidaCintura.setText("0.0");

        jlabelMedidaPeso.setText("0.0");

        jlabelMedidaGluteos.setText("0.0");

        jlabelMedidaCadera.setText("0.0");

        jlabelMedidaPiernas.setText("0.0");

        jbuttonMedidasEditar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonMedidasEditar.setText("Editar");
        jbuttonMedidasEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMedidasEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlabelMedidaCintura, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jlabelMedidaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelMedidaBiceps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelMedidaPectoral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelMedidaAbdomen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonMedidasAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonMedidasEditar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25)
                            .addComponent(jLabel28)
                            .addComponent(jLabel27))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabelMedidaPiernas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelMedidaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelMedidaGluteos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlabelMedidaCadera, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel28)
                            .addComponent(jlabelMedidaFecha)
                            .addComponent(jlabelMedidaPeso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel25)
                            .addComponent(jlabelMedidaBiceps)
                            .addComponent(jlabelMedidaGluteos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel26)
                            .addComponent(jlabelMedidaPectoral)
                            .addComponent(jlabelMedidaCadera))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel27)
                            .addComponent(jlabelMedidaAbdomen)
                            .addComponent(jlabelMedidaPiernas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbuttonMedidasEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(jlabelMedidaCintura))))
                    .addComponent(jbuttonMedidasAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Membresia"));

        jLabel15.setText("Vence");

        jLabel16.setText("Descripcion");

        jbuttonMembresiaAgregar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonMembresiaAgregar.setText("Agregar");
        jbuttonMembresiaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMembresiaAgregarActionPerformed(evt);
            }
        });

        jLabel7.setText("Precio");

        jlabelMembresiaVence.setText("{}");

        jlabelMembresiaPrecio.setText("0.0");

        jxlabelMembresiaDescripcion.setText("{}");
        jxlabelMembresiaDescripcion.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jxlabelMembresiaDescripcion.setLineWrap(true);

        jbuttonMembresiaEditar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonMembresiaEditar.setText("Editar");
        jbuttonMembresiaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMembresiaEditarActionPerformed(evt);
            }
        });

        jLabel1.setText("$");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel7))
                .addGap(93, 93, 93)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabelMembresiaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlabelMembresiaVence, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel16)
                .addGap(33, 33, 33)
                .addComponent(jxlabelMembresiaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbuttonMembresiaAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbuttonMembresiaEditar)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbuttonMembresiaAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbuttonMembresiaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabelMembresiaVence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jlabelMembresiaPrecio)
                                .addComponent(jLabel1)))
                        .addComponent(jxlabelMembresiaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbuttonNuevoCliente.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jbuttonNuevoCliente.setText("Nuevo");
        jbuttonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonNuevoClienteActionPerformed(evt);
            }
        });

        jbuttonActualizarListaNombresClientes.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jbuttonActualizarListaNombresClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymadminnh/img/icon2.png"))); // NOI18N
        jbuttonActualizarListaNombresClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActualizarListaNombresClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelClienteDatos2Layout = new javax.swing.GroupLayout(panelClienteDatos2);
        panelClienteDatos2.setLayout(panelClienteDatos2Layout);
        panelClienteDatos2Layout.setHorizontalGroup(
            panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteDatos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelClienteDatos2Layout.createSequentialGroup()
                        .addGroup(panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(panelClienteDatos2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autoComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonActualizarListaNombresClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbuttonMostrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        panelClienteDatos2Layout.setVerticalGroup(
            panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteDatos2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(5, 5, 5)
                .addGroup(panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbuttonMostrarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jbuttonActualizarListaNombresClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(autoComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jScrollPane1.setViewportView(panelClienteDatos2);

        panelPrincipal.addTab("Clientes", jScrollPane1);

        jPanel2.setPreferredSize(new java.awt.Dimension(700, 520));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nueva Asistencia"));

        jLabel34.setText("Nombre:");

        jLabel35.setText("Ultima Asistencia:");

        jLabel36.setText("Fecha Nueva:");

        jxdatepickerAsistenciasNuevaFecha.setDate(new Date());
        this.jxdatepickerAsistenciasNuevaFecha.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

        jLabel37.setText("Hora:");

        jbuttonGuardarAsistencia.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonGuardarAsistencia.setText("Guardar");
        jbuttonGuardarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonGuardarAsistenciaActionPerformed(evt);
            }
        });

        jbuttonActualizarListaNombresAsistencias.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jbuttonActualizarListaNombresAsistencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gymadminnh/img/icon2.png"))); // NOI18N
        jbuttonActualizarListaNombresAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActualizarListaNombresAsistenciasActionPerformed(evt);
            }
        });

        jcbHoras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        jcbHoras.setSelectedIndex(12);

        jcbMins.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "05", "10", "15", "20", "25", "30", "35", "40", "45", "50", "55" }));

        jbuttonMostrarAsistencia.setText("Mostrar");
        jbuttonMostrarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMostrarAsistenciaActionPerformed(evt);
            }
        });

        jlabelAsistenciaUltimaFecha.setText("dd/mm/aaaa");

        jLabel3.setText("Nombre:");

        jlabelAsistenciasNombre.setText("{nombre}");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel34)
                            .addComponent(jLabel37))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonGuardarAsistencia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jxdatepickerAsistenciasNuevaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(autocomboboxAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonActualizarListaNombresAsistencias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbuttonMostrarAsistencia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlabelAsistenciaUltimaFecha)
                                .addGap(63, 63, 63)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jlabelAsistenciasNombre)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbuttonMostrarAsistencia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbuttonActualizarListaNombresAsistencias, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(autocomboboxAsistencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel35)
                                    .addComponent(jlabelAsistenciaUltimaFecha)
                                    .addComponent(jLabel3)
                                    .addComponent(jlabelAsistenciasNombre))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jxdatepickerAsistenciasNuevaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(jcbHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbMins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jbuttonGuardarAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Asistencia Por Dia"));

        jxdatepickerAsistenciasDelDia.setDate(new Date());
        this.jxdatepickerAsistenciasDelDia.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

        jLabel38.setText("Seleccionar Dia:");

        jbuttonActualizarTablaAsistencias.setText("Actualizar Tabla");
        jbuttonActualizarTablaAsistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActualizarTablaAsistenciasActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "idCliente", "Nombre", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(jxdatepickerAsistenciasDelDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbuttonActualizarTablaAsistencias)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jxdatepickerAsistenciasDelDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(jbuttonActualizarTablaAsistencias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel2);

        panelPrincipal.addTab("Asistencias", jScrollPane4);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo"));

        jxdatepickerFinanzasNuevo.setDate(new Date());
        this.jxdatepickerFinanzasNuevo.setFormats(new SimpleDateFormat("dd/MM/yyyy"));

        jLabel4.setText("Fecha:");

        jLabel5.setText("Costo:");

        jLabel6.setText("Descripcion:");

        jbuttonFinanzasGuardar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonFinanzasGuardar.setText("Guardar");
        jbuttonFinanzasGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonFinanzasGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 145, Short.MAX_VALUE)
                .addComponent(jbuttonFinanzasGuardar))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 57, Short.MAX_VALUE)
                .addComponent(jbuttonFinanzasGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel17.setText("Tipo:");

        jcbFinanzasTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ingreso", "Egreso" }));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbFinanzasTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxdatepickerFinanzasNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFinanzasCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFinanzasDescr, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jxdatepickerFinanzasNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jcbFinanzasTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfFinanzasCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfFinanzasDescr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));

        jLabel8.setText("Seleccionar Mes:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "idFinanzas", "Descripcion", "Precio"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jcbFinanzasMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel9.setText("Ano:");

        jtfFinanzasResumenAno.setText("0000");
        int year = Calendar.getInstance().get(Calendar.YEAR);
        this.jtfFinanzasResumenAno.setText(String.valueOf(year));

        jbuttonFinanzasMostrarResumen.setText("Mostrar");
        jbuttonFinanzasMostrarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonFinanzasMostrarResumenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jcbFinanzasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfFinanzasResumenAno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonFinanzasMostrarResumen)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbFinanzasMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfFinanzasResumenAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonFinanzasMostrarResumen))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelPrincipal.addTab("Finanzas", jPanel4);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen por mes"));

        jLabel14.setText("Elegir mes/ano:");

        jcbResumenMembsMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        jtfResumenMembsAno.setText("2012");
        this.jtfFinanzasResumenAno.setText(String.valueOf(year));

        jtableResumenMembresias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "IDCLIENTE", "NOMBRE", "FECHA_INICIO", "DURACION", "DESCRIPCION", "PRECIO"
            }
        ));
        jScrollPane3.setViewportView(jtableResumenMembresias);

        jbuttonResumenMembresiasMostrar.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jbuttonResumenMembresiasMostrar.setText("Mostrar");
        jbuttonResumenMembresiasMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonResumenMembresiasMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jcbResumenMembsMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfResumenMembsAno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbuttonResumenMembresiasMostrar))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jcbResumenMembsMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfResumenMembsAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonResumenMembresiasMostrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        panelPrincipal.addTab("Resumen Membresias", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonNuevoClienteActionPerformed
        JFrameCliente jfc = new JFrameCliente(true, clienteActual, nombres);
        jfc.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        jfc.setVisible(true);
    }//GEN-LAST:event_jbuttonNuevoClienteActionPerformed

    private void jbuttonMembresiaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMembresiaAgregarActionPerformed
        if (clienteActual.getIdCliente() > 0) {
            JFrameMembresia jfm = new JFrameMembresia(true, clienteActual);
            jfm.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            jfm.setVisible(true);
        }
    }//GEN-LAST:event_jbuttonMembresiaAgregarActionPerformed

    private void jbuttonMedidasEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMedidasEditarActionPerformed
        if (clienteActual.getListaMedidas().size() > 0) {
            JFrameMedidas jfm = new JFrameMedidas(false, clienteActual);
            jfm.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            jfm.setVisible(true);
        }
    }//GEN-LAST:event_jbuttonMedidasEditarActionPerformed

    private void jbuttonMedidasAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMedidasAgregarActionPerformed
        if (clienteActual.getIdCliente() > 0) {
            JFrameMedidas jfm = new JFrameMedidas(true, clienteActual);
            jfm.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            jfm.setVisible(true);
        }
    }//GEN-LAST:event_jbuttonMedidasAgregarActionPerformed

    private void jbuttonModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonModificarClienteActionPerformed
        if (clienteActual.getIdCliente() > 0 ) {
            JFrameCliente jfc = new JFrameCliente(false, clienteActual, nombres);
            jfc.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            jfc.setVisible(true);
        }
    }//GEN-LAST:event_jbuttonModificarClienteActionPerformed

    private void jbuttonMembresiaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMembresiaEditarActionPerformed
        if (clienteActual.getListaMembresias().size() > 0 ) {
            JFrameMembresia jfm = new JFrameMembresia(false, clienteActual);
            jfm.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            jfm.setVisible(true);
        }
    }//GEN-LAST:event_jbuttonMembresiaEditarActionPerformed

    private void jbuttonActualizarListaNombresClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActualizarListaNombresClientesActionPerformed
        actualizarListaNombres(autoComboBoxClientes);
    }//GEN-LAST:event_jbuttonActualizarListaNombresClientesActionPerformed

    private void jbuttonMostrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMostrarClienteActionPerformed
        String str = String.valueOf(this.autoComboBoxClientes.getSelectedItem());
        if (str == null || str.isEmpty() || str.equals("") || str.equals("null")) {
            JOptionPane.showMessageDialog(this, "El campo de nombre no puede estar vacio.");
        } else {
            if (str.indexOf(",") < 0) {
                JOptionPane.showMessageDialog(this, "Cliente no esta en la lista.");
            } else {
                String idCliente = str.split(",")[1];
                int id = Integer.parseInt(idCliente);
                clienteActual = new DataUtils().getClienteDB(id);
                if (clienteActual.getIdCliente() < 1 ) {
                    JOptionPane.showMessageDialog(this, "No se encontro el cliente.");
                } else {
                    actualizarClienteActual();
                }

            }
        }
    }//GEN-LAST:event_jbuttonMostrarClienteActionPerformed

    private void jbuttonActualizarListaNombresAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActualizarListaNombresAsistenciasActionPerformed
        this.actualizarListaNombres(autocomboboxAsistencias);
    }//GEN-LAST:event_jbuttonActualizarListaNombresAsistenciasActionPerformed

    private void jbuttonGuardarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonGuardarAsistenciaActionPerformed
        Calendar cal = Calendar.getInstance();
        cal.setTime(this.jxdatepickerAsistenciasNuevaFecha.getDate());
        int horas = this.jcbHoras.getSelectedIndex();
        int mins = Integer.parseInt(String.valueOf(this.jcbMins.getSelectedItem()));
        cal.add(Calendar.HOUR_OF_DAY, horas);
        cal.add(Calendar.MINUTE, mins);

        Asistencia a = new Asistencia();
        a.setFechaAsistencia(cal.getTime());
        
        int resultado = 0;
        
        resultado = new DataUtils().agregarAsistenciaDB(a, asistenteActual.getIdCliente());
        
        if (resultado == 1) {
            JOptionPane.showMessageDialog(this, "Datos guardados.");

        } else {
            JOptionPane.showMessageDialog(this, "Hubo un error al guardar los datos. Los datos no han sido guardados.");
        }
        
        limpiaAsistenciaNueva();
    }//GEN-LAST:event_jbuttonGuardarAsistenciaActionPerformed

    private void jbuttonMostrarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMostrarAsistenciaActionPerformed
        String str = String.valueOf(this.autocomboboxAsistencias.getSelectedItem());
        if (str == null || str.isEmpty() || str.equals("") || str.equals("null")) {
            JOptionPane.showMessageDialog(this, "El campo de nombre no puede estar vacio.");
        } else {
            if (str.indexOf(",") < 0) {
                JOptionPane.showMessageDialog(this, "Cliente no esta en la lista.");
            } else {
                String idCliente = str.split(",")[1];
                int id = Integer.parseInt(idCliente);
                asistenteActual = new DataUtils().getClienteDB(id);
                if (asistenteActual.getIdCliente() < 1 ) {
                    JOptionPane.showMessageDialog(this, "No se encontro el cliente.");
                } else {
                    asistenteActual.setListaAsistencias(new DataUtils().obtenerAsistenciasClienteDB(asistenteActual.getIdCliente()));
                    actualizarAsistenteActual();
                    
                }
            }
        }
    }//GEN-LAST:event_jbuttonMostrarAsistenciaActionPerformed

    private void jbuttonActualizarTablaAsistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActualizarTablaAsistenciasActionPerformed
        this.jTable1.setModel(new DataUtils().obtenerAsistenciasDiaDB(this.jxdatepickerAsistenciasDelDia.getDate()));
        this.jTable1.updateUI();
    }//GEN-LAST:event_jbuttonActualizarTablaAsistenciasActionPerformed

    private void jbuttonFinanzasMostrarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonFinanzasMostrarResumenActionPerformed
        int mes = this.jcbFinanzasMes.getSelectedIndex() + 1;
        String mesStr = String.valueOf(mes);
        if ( mes < 10)
            mesStr = "0" + mes;
        String anoStr = this.jtfFinanzasResumenAno.getText();
        int ano = 0;
        try {
            ano = Integer.parseInt(anoStr);
        } catch (Exception e){
            ano = -1;
            JOptionPane.showMessageDialog(this, "Ano no valido.");
        }
        if ( ano > 0 ){
            this.jTable2.setModel(new DataUtils().obtenerResumenFinanzasDB(ano, mesStr));
            this.jTable2.updateUI();
        }
    }//GEN-LAST:event_jbuttonFinanzasMostrarResumenActionPerformed

    private void jbuttonFinanzasGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonFinanzasGuardarActionPerformed
        Date fecha = this.jxdatepickerFinanzasNuevo.getDate();
        Double precio = 0.0;
        String descr = this.jtfFinanzasDescr.getText();
        boolean ok = true;
        try {
            precio = Double.parseDouble(this.jtfFinanzasCosto.getText());
        } catch (Exception e) {
            ok = false;
        }
        if ( ok ) {
            int resultado = 0;
            if ( this.jcbFinanzasTipo.getSelectedIndex() == 1 ){
                precio = precio * -1;
            }
            resultado = new DataUtils().agregarMovimiento(fecha, precio, descr);
            if (resultado == 1) {
                JOptionPane.showMessageDialog(this, "Datos guardados.");
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al guardar los datos. Los datos no han sido guardados.");
            }
        }
        
        this.jxdatepickerFinanzasNuevo.setDate(new Date());
        this.jxdatepickerFinanzasNuevo.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        
        this.jtfFinanzasCosto.setText("0.0");
        this.jtfFinanzasDescr.setText("");
    }//GEN-LAST:event_jbuttonFinanzasGuardarActionPerformed

    private void jbuttonResumenMembresiasMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonResumenMembresiasMostrarActionPerformed
        int mes = this.jcbResumenMembsMes.getSelectedIndex() + 1;
        String mesStr = String.valueOf(mes);
        if ( mes < 10)
            mesStr = "0" + mes;
        String anoStr = this.jtfResumenMembsAno.getText();
        int ano = 0;
        try {
            ano = Integer.parseInt(anoStr);
        } catch (Exception e){
            ano = -1;
            JOptionPane.showMessageDialog(this, "Ano no valido.");
        }
        if ( ano > 0 ){
            this.jtableResumenMembresias.setModel(new DataUtils().obtenerResumenMembresiasDB(ano, mesStr));
            this.jtableResumenMembresias.updateUI();
        }
    }//GEN-LAST:event_jbuttonResumenMembresiasMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.jidesoft.swing.AutoCompletionComboBox autoComboBoxClientes;
    private com.jidesoft.swing.AutoCompletionComboBox autocomboboxAsistencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbuttonActualizarListaNombresAsistencias;
    private javax.swing.JButton jbuttonActualizarListaNombresClientes;
    private javax.swing.JButton jbuttonActualizarTablaAsistencias;
    private javax.swing.JButton jbuttonEditarCliente;
    private javax.swing.JButton jbuttonFinanzasGuardar;
    private javax.swing.JButton jbuttonFinanzasMostrarResumen;
    private javax.swing.JButton jbuttonGuardarAsistencia;
    private javax.swing.JButton jbuttonMedidasAgregar;
    private javax.swing.JButton jbuttonMedidasEditar;
    private javax.swing.JButton jbuttonMembresiaAgregar;
    private javax.swing.JButton jbuttonMembresiaEditar;
    private javax.swing.JButton jbuttonMostrarAsistencia;
    private javax.swing.JButton jbuttonMostrarCliente;
    private javax.swing.JButton jbuttonNuevoCliente;
    private javax.swing.JButton jbuttonResumenMembresiasMostrar;
    private javax.swing.JComboBox jcbFinanzasMes;
    private javax.swing.JComboBox jcbFinanzasTipo;
    private javax.swing.JComboBox jcbHoras;
    private javax.swing.JComboBox jcbMins;
    private javax.swing.JComboBox jcbResumenMembsMes;
    private javax.swing.JLabel jlabelAsistenciaUltimaFecha;
    private javax.swing.JLabel jlabelAsistenciasNombre;
    private javax.swing.JLabel jlabelDireccion;
    private javax.swing.JLabel jlabelEdad;
    private javax.swing.JLabel jlabelEmail;
    private javax.swing.JLabel jlabelMedidaAbdomen;
    private javax.swing.JLabel jlabelMedidaBiceps;
    private javax.swing.JLabel jlabelMedidaCadera;
    private javax.swing.JLabel jlabelMedidaCintura;
    private javax.swing.JLabel jlabelMedidaFecha;
    private javax.swing.JLabel jlabelMedidaGluteos;
    private javax.swing.JLabel jlabelMedidaPectoral;
    private javax.swing.JLabel jlabelMedidaPeso;
    private javax.swing.JLabel jlabelMedidaPiernas;
    private javax.swing.JLabel jlabelMembresiaPrecio;
    private javax.swing.JLabel jlabelMembresiaVence;
    private javax.swing.JLabel jlabelNombre;
    private javax.swing.JLabel jlabelTelefono;
    private javax.swing.JTable jtableResumenMembresias;
    private javax.swing.JTextField jtfFinanzasCosto;
    private javax.swing.JTextField jtfFinanzasDescr;
    private javax.swing.JTextField jtfFinanzasResumenAno;
    private javax.swing.JTextField jtfResumenMembsAno;
    private org.jdesktop.swingx.JXDatePicker jxdatepickerAsistenciasDelDia;
    private org.jdesktop.swingx.JXDatePicker jxdatepickerAsistenciasNuevaFecha;
    private org.jdesktop.swingx.JXDatePicker jxdatepickerFinanzasNuevo;
    private org.jdesktop.swingx.JXLabel jxlabelMembresiaDescripcion;
    private javax.swing.JPanel panelClienteDatos2;
    private javax.swing.JTabbedPane panelPrincipal;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosGenerales() {
        this.jlabelNombre.setText(clienteActual.getNombre());
        this.jlabelTelefono.setText(clienteActual.getTelefono());
        this.jlabelEdad.setText(String.valueOf(clienteActual.getEdad()));
        this.jlabelEmail.setText(clienteActual.getEmail());
        this.jlabelDireccion.setText(clienteActual.getDireccion());
    }

    private void cargarMedidas() {
        ArrayList<MedidasCliente> lmc = new DataUtils().getMedidasCliente(clienteActual.getIdCliente());
        clienteActual.setListaMedidas(lmc);

        if ( lmc.size() > 0 ){
            MedidasCliente um = lmc.get(lmc.size()-1);
            Date fecha = um.getFecha();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            this.jlabelMedidaFecha.setText(sdf.format(fecha).toString());
            this.jlabelMedidaBiceps.setText(um.getBicepDer() + " / " + um.getBicepIzq());
            this.jlabelMedidaPectoral.setText(String.valueOf( um.getPectoral() ) );
            this.jlabelMedidaAbdomen.setText(String.valueOf(um.getAbdomen()));
            this.jlabelMedidaCintura.setText(String.valueOf(um.getCintura()));
            this.jlabelMedidaPeso.setText(String.valueOf(um.getPeso()));
            this.jlabelMedidaGluteos.setText(String.valueOf(um.getGluteos()));
            this.jlabelMedidaCadera.setText(String.valueOf(um.getCadera()));
            this.jlabelMedidaPiernas.setText(um.getPiernaDer() + " / " + um.getPiernaIzq());
        }
    }

    private void cargarMembresias() {
        ArrayList<Membresia> mems = new DataUtils().getMembresias(clienteActual.getIdCliente());
        clienteActual.setListaMembresias(mems);
        
        if ( mems.size() > 0 ) {
            Membresia um = mems.get(mems.size()-1);
            
            Date fechaInicio = um.getFechaInicio();
            Calendar cal = new GregorianCalendar();
            cal.setTime(fechaInicio);
            cal.add(Calendar.MONTH, um.getDuracion());
            Date fechaVence = cal.getTime();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            
            this.jlabelMembresiaVence.setText(sdf.format(fechaVence));
            this.jlabelMembresiaPrecio.setText(String.valueOf(um.getPrecio()));
            this.jxlabelMembresiaDescripcion.setText(um.getDescripcion());
        }
        
    }

    private void actualizarListaNombres(AutoCompletionComboBox accb) {
        actualizarListaClientes();
        accb.removeAllItems();
        for (int i = 0; i <listaClientes.size() ; i++){
            Cliente c = listaClientes.get(i);
            accb.insertItemAt(c.getNombre()+","+c.getIdCliente(), i );
        }
    }
    
    private void actualizarListaClientes(){
        this.listaClientes = new DataUtils().getTodosClientes();
    }

    private void limpiarClientesLabels() {
        this.jlabelNombre.setText("{nombre}");
        this.jlabelTelefono.setText("{telefono}");
        this.jlabelEdad.setText("{edad}");
        this.jlabelEmail.setText("{email}");
        this.jlabelDireccion.setText("{direccion}");
        
        this.jlabelMedidaFecha.setText("{fecha}");
        this.jlabelMedidaBiceps.setText("0.0");
        this.jlabelMedidaPectoral.setText("0.0");
        this.jlabelMedidaAbdomen.setText("0.0");
        this.jlabelMedidaCintura.setText("0.0");
        this.jlabelMedidaPeso.setText("0.0");
        this.jlabelMedidaGluteos.setText("0.0");
        this.jlabelMedidaCadera.setText("0.0");
        this.jlabelMedidaPiernas.setText("0.0");
        
        this.jlabelMembresiaVence.setText("{fecha}");
        this.jlabelMembresiaPrecio.setText("{0.0}");
        this.jxlabelMembresiaDescripcion.setText("{descripcion}");
    }

    private void limpiaAsistenciaNueva() {
//        this.autocomboboxAsistencias.setSelectedItem("");
        this.jlabelAsistenciasNombre.setText("{nombre}");
        this.jlabelAsistenciaUltimaFecha.setText("dd/mm/aaaa");
        this.jxdatepickerAsistenciasNuevaFecha.setDate(new Date());
        this.jcbHoras.setSelectedIndex(12);
        this.jcbMins.setSelectedIndex(0);
    }
}
